---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: awx-secret-tls
    type: kubernetes.io/tls
    files:
      - tls.crt
      - tls.key

  - name: awx-postgres-configuration
    type: Opaque
    literals:
      - host=awx-postgres
      - port=5432
      - database=awx
      - username=awx
      - password=P0plar1935
      - type=managed

  - name: awx-admin-password
    type: Opaque
    literals:
      - password=P0plar1935

  # Temporary workaround to suppress errors from AWX Operator 0.21.0.
  # Refer: https://github.com/kurokobo/awx-on-k3s/issues/74
  - name: redhat-operators-pull-secret
    files:
      - .dockerconfigjson=dockerconfig.json
    type: kubernetes.io/dockerconfigjson

resources:
  - pv.yaml
  - pvc.yaml
  - awx.yaml
